//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDK.XrmToolBox.StorageCleaner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDK.XrmToolBox.StorageCleaner.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch  version=&quot;1.0&quot; {1}&gt;
        ///  &lt;entity name=&quot;audit&quot; &gt;
        ///    &lt;attribute name=&quot;auditid&quot; /&gt;
        ///    &lt;filter&gt;
        ///      &lt;condition attribute=&quot;createdon&quot; operator=&quot;olderthan-x-months&quot; value=&quot;{0}&quot; /&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string FetchXml_Audit {
            get {
                return ResourceManager.GetString("FetchXml_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; {1}&gt;
        ///  &lt;entity name=&quot;asyncoperation&quot; &gt;
        ///    &lt;attribute name=&quot;asyncoperationid&quot; /&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;operationtype&quot; operator=&quot;eq&quot; value=&quot;13&quot; /&gt;
        ///      &lt;condition attribute=&quot;statuscode&quot; operator=&quot;eq&quot; value=&quot;30&quot; /&gt;
        ///      &lt;condition attribute=&quot;completedon&quot; operator=&quot;olderthan-x-months&quot; value=&quot;{0}&quot; /&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string FetchXml_BulkDelete {
            get {
                return ResourceManager.GetString("FetchXml_BulkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; {1}&gt;
        ///  &lt;entity name=&quot;asyncoperation&quot; &gt;
        ///    &lt;attribute name=&quot;asyncoperationid&quot;  /&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;operationtype&quot; operator=&quot;in&quot; &gt;
        ///        &lt;value&gt;2&lt;/value&gt;
        ///        &lt;value&gt;10&lt;/value&gt;
        ///      &lt;/condition&gt;
        ///      &lt;condition attribute=&quot;statuscode&quot; operator=&quot;eq&quot; value=&quot;30&quot; /&gt;
        ///      &lt;condition attribute=&quot;completedon&quot; operator=&quot;olderthan-x-months&quot; value=&quot;{0}&quot; /&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string FetchXml_BulkEmailAndWorkflow {
            get {
                return ResourceManager.GetString("FetchXml_BulkEmailAndWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; {1} &gt;
        ///  &lt;entity name=&quot;asyncoperation&quot; &gt;
        ///    &lt;attribute name=&quot;asyncoperationid&quot; /&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;operationtype&quot; operator=&quot;eq&quot; value=&quot;5&quot; /&gt;
        ///      &lt;condition attribute=&quot;statuscode&quot; operator=&quot;eq&quot; value=&quot;30&quot; /&gt;
        ///      &lt;condition attribute=&quot;completedon&quot; operator=&quot;olderthan-x-months&quot; value=&quot;{0}&quot; /&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string FetchXml_BulkImport {
            get {
                return ResourceManager.GetString("FetchXml_BulkImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; {2}&gt;
        ///  &lt;entity name=&quot;email&quot; &gt;
        ///    &lt;attribute name=&quot;activityid&quot; /&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;createdon&quot; value=&quot;{0}&quot; operator=&quot;olderthan-x-months&quot; /&gt;
        ///    &lt;/filter&gt;
        ///    &lt;link-entity name=&quot;activitymimeattachment&quot; from=&quot;objectid&quot; to=&quot;activityid&quot; alias=&quot;ac&quot; &gt;
        ///      &lt;filter type=&quot;and&quot; &gt;
        ///        &lt;condition attribute=&quot;filesize&quot; operator=&quot;gt&quot; value=&quot;{1}&quot; /&gt;
        ///      &lt;/filter&gt;
        ///    &lt;/link-entity&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string FetchXml_EmailWithAttachements {
            get {
                return ResourceManager.GetString("FetchXml_EmailWithAttachements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; {2} &gt;
        ///  &lt;entity name=&quot;annotation&quot; &gt;
        ///    &lt;attribute name=&quot;annotationid&quot; /&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;filesize&quot; operator=&quot;gt&quot; value=&quot;{1}&quot; /&gt;
        ///      &lt;condition attribute=&quot;createdon&quot; operator=&quot;olderthan-x-months&quot; value=&quot;{0}&quot; /&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string FetchXml_NotesWithAttachments {
            get {
                return ResourceManager.GetString("FetchXml_NotesWithAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; {1} &gt;
        ///  &lt;entity name=&quot;asyncoperation&quot; &gt;
        ///    &lt;attribute name=&quot;asyncoperationid&quot;/&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;operationtype&quot; operator=&quot;in&quot; &gt;
        ///        &lt;value&gt;10&lt;/value&gt;
        ///      &lt;/condition&gt;
        ///      &lt;condition attribute=&quot;statuscode&quot; operator=&quot;eq&quot; value=&quot;10&quot; /&gt;
        ///      &lt;condition attribute=&quot;completedon&quot; operator=&quot;olderthan-x-months&quot; value=&quot;{0}&quot; /&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string FetchXml_SuspendedWorkflow {
            get {
                return ResourceManager.GetString("FetchXml_SuspendedWorkflow", resourceCulture);
            }
        }
    }
}
